config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'profiles/show'
  get "users/:username" => "profiles#show", as: "profile"

  post "posts" => "pages#new_post", as: "new_post"
  post 'posts' => 'posts#post', as: "post_post"
  get "sessions/new" => "sessions#new", as: "sign_in"
  post "sessions" => "sessions#create"
  delete "sessions" => "sessions#signout", as: "sign_out"
  get "signup" => "sessions#signup", as: :signup
  post "signup" => "sessions#create_user", as: :create_user

end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true
  validates :password, presence: true, confirmation: true
  has_many :followings
  has_many :followers, through: :followings
  has_many :posts

  scope :following, -> (current_user) { joins(:followings).where('follower_id = ?', current_user) }

  def self.create_user_with_messages(user_name, password, messages)
    u = create(name: user_name, password: password)
    posts.each do |post|
      u.posts.create post: post
    end
    u
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user = User.find session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action do
    if session[:user_id].present?
    else
      redirect_to sign_in_path
    end
  end

  def index
    @users = User.all
    @posts = current_user.posts.order("created_at desc")
    @post = Post.new
    @allposts = Post.all
    @followings = Following.all
    if params[:unfollow_user_id]
      @followings = Following.where(user_id: params[:unfollow_user_id], follower_id: current_user.id )
      @followings.first.destroy
      redirect_to root_path, :flash => { :info => "The user was successfully unfollowed" }
    end
  end

  def new_post
    @post = Post.new(params.require(:post).permit(:post))
    @post.user = current_user
    if @post.save
      redirect_to root_path
    else
      render :index
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action do
    if session[:user_id].present?
    else
      redirect_to sign_in_path
    end
  end

  def new
    @post = Post.new
  end

  def post
    @post = Post.new(params.require(:post).permit(:post))
    @post.user = current_user
    if @post.save
      redirect_to root_path
    else
      render :index
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by name: params[:name]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    name = params[:name]
    password = params[:password]
    user = User.find_by name: name
    if user.password == password
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def signout
    session[:user_id] = nil
    redirect_to root_path
  end

  def signup
    @user = User.new
  end

  def create_user
    @user = User.new(params.require(:user).permit(:name, :password,:password_confirmation, :photo_url))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :signup
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rayoflight</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/cerulean/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome To Ultraviolet <%= link_to @current_user.name, profile_path(@current_user.name) %></h1>
<%= button_to "Signout", sign_out_path, method: :delete, data: { confirm: "Are you sure?" } %>

<p id="notice"><%= notice %></p>

<%= form_for @post, url: new_post_path do |f| %>
<%= f.text_area :post %>
<%= f.submit %>
<% end %>


<h2> Your Timeline </h2>
<div class="posts">

  <ul>
    <% @posts.each do |post| %>
    <li class="post">
      <%= post.post %>
      <br/>
      On <%= post.created_at.strftime("%b %e, %l:%M %p") %>
    </li>
    <% end %>
  </ul>
  <hr>
  <h1> People you are currently following : </h1>

  <% @followings.each do |following| %>
  <h1><%= link_to following.name, profile_path(following.name) %> </h1>
  <%= link_to "Unfollow", root_path(:unfollow_user_id => following.id), method: "get" %>
  <ul>
    <% following.posts.each do |post| %>
    <li class="post">
      <%= post.post %>
      <br/>
      On <%= post.created_at.strftime("%b %e, %l:%M %p") %>
    </li>
    <% end %>
  </ul>
  <% end %>

</div>

app/views/posts/new.html.erb
<h1>Make a post</h1>
<% form_for @post do |f| %>
<div>
  <% f.label :post %>
  <% f.text_field :post %>
</div>
<div>
  <%= f.submit "post" %>
</div>
<% end %>

app/views/profiles/show.html.erb
<h1>Profile for <%= @user.name %></h1>

<h3>....Posts.....</h3>

<div class="posts">

  <ul>
    <% @user.posts.each do |post| %>
    <li class="post">
      <%= post.post %>
      <br/>
      On <%= post.created_at.strftime("%b %e, %l:%M %p") %>
    </li>
    <% end %>
  </ul>

</div>

<%= link_to "HOME", sign_in_path %>
<%= link_to "back", root_path %>